### ISSUE TITLE
introduce linter/formater

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs-loaders/nodejs-loaders#31]
We need a linter/formater to unsure that our code will have same style everytime

Possible way to handle that
- [standard](https://www.google.com/search?client=safari&rls=en&q=standard+linting&ie=UTF-8&oe=UTF-8)
- [noe standard](https://github.com/neostandard/neostandard)
- [eslint](https://eslint.org) + [prettier](https://prettier.io)
- [biome](https://biomejs.dev)

Things need to be done:
- have the `format` script that call the linter and the formater
- have vsc settings enabled to directly format the code on save (because Jakob and I use vsc)
- have commit hooks (maybe husky)
- have pr/main workflow that check code quality

**Comment by JakobJingleheimer** [comment]
Let's go for biome :)
